### PR TITLE
Allow installation on PHP 8.1

### PR DESCRIPTION
**Pull request by cedric-anne**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

Allow installation on PHP 8.1

### CODE REVIEW

**Comment by cedric-anne** [comment]
Hi,

Looks like it is necessary to update composer.json on A and B laminas components which depends on C, D, E and F laminas components which depends on G, H, I, J, K, L laminas components and so on.
I do not have time to check all of them. So feel free to do whatever you want with this PR.

Regards

**Comment by Ocramius** [comment]
> I do not have time to check all of them. So feel free to do whatever you want with this PR.

 nobody here "has time" - we're just throwing in the spare time we can, and we make merges happen when viable.

**Comment by cedric-anne** [comment]
> nobody here "has time" - we're just throwing in the spare time we can, and we make merges happen when viable.

I meaned that I was pretty sure to not be able to do check on the whole chain. I prefered to be honest and not just let a stale PR.
I also sometimes devote time to the PHP ecosystem when I think I can finish my job.

By the way, after my PR https://github.com/laminas/laminas-cache/pull/170 was refused on laminas-cache component, I figured out that adding compatibility to PHP 8.1 here is not possible until a stable 3.x version of laminas-cache component is released.

**Comment by froschdesign** [comment]
@cedric-anne 
> …I figured out that adding compatibility to PHP 8.1 here is not possible until a stable 3.x version of laminas-cache component is released.

The support for PHP 8.1 can be added. Compare with other packages which used also laminas-cache as a [_soft_ dependency](https://github.com/laminas/laminas-i18n/blob/fea1847eba42fabccedccfd3b12361196fe35bf5/composer.json#L33-L34). Example: https://github.com/laminas/laminas-paginator/pull/32

**Comment by boesing** [comment]
Seriously, I would prefer getting rid of all these `laminas-cache` dependencies in all those components. These components should use PSR-16 or PSR-6 interfaces instead so we can simply just work with these interfaces rather than providing magic factory logic which is more and more deprecated in `laminas-cache`.

Good to know that we have so many dependencies on `laminas-cache`, so there is really plenty of work left even tho I am ready with `laminas-cache` v3 with PHP 8.1. 
I'm glad that I did not make any changes to the `StorageInterface` which is mainly used in upstream components but the `StorageFactory` usage is so widely used that it seems to require glue code for MVC and mezzio bootstrap to provide some static factory alternative to replace all those `StorageFactory` abominations.

Thanks for pointing me on this @cedric-anne @froschdesign

**Comment by froschdesign** [comment]
@boesing 
> …I would prefer getting rid of all these laminas-cache dependencies in all those components.

This is already planned for the next major version and a decorator with PSR support will then be used for the translator.

**Comment by cedric-anne** [comment]
> The support for PHP 8.1 can be added. Compare with other packages which used also laminas-cache as a [_soft_ dependency](https://github.com/laminas/laminas-i18n/blob/fea1847eba42fabccedccfd3b12361196fe35bf5/composer.json#L33-L34). Example: [laminas/laminas-paginator#32](https://github.com/laminas/laminas-paginator/pull/32)

I tried, but there are errors in tests suite due to laminas-cache component methods signatures in PHP 8.1 :/
see https://github.com/cedric-anne/laminas-i18n/runs/3997963048?check_suite_focus=true

**Comment by froschdesign** [comment]
@cedric-anne 
laminas-paginator has the same dependency to cache component and for the PHP 8.1 support the same steps must be adapted for laminas-i18n:

https://github.com/laminas/laminas-paginator/pull/32/files#diff-3fb49ad00d3736f1ca8276f568f5d8bbe8c1604f6187ab5ecf921e1012f47c98

https://github.com/laminas/laminas-paginator/pull/32/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

**Comment by cedric-anne** [comment]
Even with components upgrade to their maximum version, I still have the error. See https://github.com/cedric-anne/laminas-i18n/tree/feature/php-8.1 .

**Comment by froschdesign** [comment]
@cedric-anne 
```
PHP Fatal error:  During inheritance of IteratorAggregate:
Uncaught Return type of Laminas\Cache\Storage\Adapter\Memory::getIterator() should either be compatible
with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should
be used to temporarily suppress the notice
```
A polyfill can help here. We already use this temporary solution in laminas-view:

* https://github.com/laminas/laminas-view/tree/2.14.x/polyfill
* https://github.com/laminas/laminas-view/blob/7ba573a745c16b4359fac558b4ef8af7426943a8/composer.json#L82

**Pull request closed without merging**
