### PR TITLE
Fixed: handling non-scalars in NumberParse filter

### LINKED ISSUE #105: Better handling of NULL values in Laminas\I18n\Filter\NumberParse
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | unsure

#### Summary

Hello,

since PHP 8.1 it's not possible to pass `null` to `NumberFormatter::parse()`:

```
Deprecated: NumberFormatter::parse(): Passing null to parameter #1 ($string) of type string is deprecated
```

see https://onlinephp.io/c/b9443.

In one of my forms I want an empty field to be parsed to `null` and otherwise to be parsed by `Laminas\I18n\Filter\NumberParse` filter. The filter chain looks like the following:

```php

use Laminas\I18n\Validator as I18nValidator;
use Laminas\I18n\Filter as I18nFilter;

return [
    [
        'name' => Filter\StringTrim::class,
    ],
    [
        'name'    => I18nFilter\NumberParse::class,
        'options' => [
            'locale' => $locale,
        ],
    ],
    [
        'name' => Filter\ToNull::class,
    ],
];
```

Problem here is that I bind an object to the form where the field value is `null` and the filter triggers the deprecation notice when I do `isValid()` on the form.

Therefor I propose to add a new option to the filter to allow null values to be passed to `filter()`.

Full test script:

```php
<?php

use Laminas\Form\Form;
use Laminas\Form\Element;
use Laminas\InputFilter\InputFilterProviderInterface;
use Laminas\I18n\Filter as I18nFilter;
use Laminas\Filter;

require 'vendor/autoload.php';

error_reporting(-1);
ini_set('display_errors', '1');

$bindObj = new class() {
    public function getArrayCopy()
    {
        return [
            'test' => null,
        ];
    }
};

$myform = new class() extends Form implements InputFilterProviderInterface{
    public function init()
    {
        $this->add([
            'type' => Element\Text::class,
            'name' => 'test'
        ]);
    }

    public function getInputFilterSpecification()
    {
        return [
            'test' => [
                'required' => false,
                'filters'  => [
                    [
                        'name' => Filter\StringTrim::class,
                    ],
                    [
                        'name'    => I18nFilter\NumberParse::class,
                        'options' => [
                            'locale' => 'en_US',
                        ],
                    ],
                    [
                        'name' => Filter\ToNull::class,
                    ],
                ]
            ],
        ];
    }
};

$myform->bind($bindObj);

$myform->setData([]);
var_dump($myform->isValid());

$myform->setData(['test' => '1,000.25']);
var_dump($myform->isValid()); // ok

```

Result:
```
Deprecated: NumberFormatter::parse(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/laminas/laminas-i18n/src/Filter/NumberParse.php on line 158

Call Stack:
    0.0003     361216   1. {main}() test.php:0
    0.0281     596600   2. Laminas\Form\Form->isValid() test.php:59
    0.0461     815360   3. Laminas\Form\Form->bindValues($values = ???, $validationGroup = ???) vendor/laminas/laminas-form/src/Form.php:478
    0.0461     815360   4. Laminas\InputFilter\BaseInputFilter->getValues() vendor/laminas/laminas-form/src/Form.php:338
    0.0461     815576   5. Laminas\InputFilter\Input->getValue() vendor/laminas/laminas-inputfilter/src/BaseInputFilter.php:423
    0.0461     815576   6. Laminas\Filter\FilterChain->filter($value = NULL) vendor/laminas/laminas-inputfilter/src/Input.php:278
    0.0462     817888   7. Laminas\I18n\Filter\NumberParse->filter($value = NULL) vendor/laminas/laminas-filter/src/FilterChain.php:245
    0.0471     818880   8. NumberFormatter->parse($string = NULL, $type = 3) vendor/laminas/laminas-i18n/src/Filter/NumberParse.php:158

test.php:59:
bool(true)
test.php:62:
bool(true)

```

### PR DESCRIPTION
**Pull request by fabiang**
`filter()` now returns `$value` as-is for non-scalar and boolean values, which fixes triggering a deprection warning since PHP 8.1.

Fix for issue #105

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### CODE REVIEW

**Comment by froschdesign** [comment]
For a bugfix please use the current release branch, which is 2.23.x:

- https://github.com/laminas/laminas-i18n/tree/2.23.x
- https://github.com/laminas/laminas-i18n/releases

More on this topic can be found in the contributing guidelines: "[What branch to issue the pull request against?](https://github.com/laminas/.github/blob/e6a512745785a1f183c92d41cbb39bbaa3fda717/CONTRIBUTING.md#what-branch-to-issue-the-pull-request-against)"

Thanks in advance! 👍🏻

**Comment by fabiang** [comment]
Rebased to 2.23.x.

**Review by gsteel — APPROVED** [review]
LGTM 👍

**Comment by gsteel** [comment]
Thanks @fabiang

**Comment by fabiang** [comment]
Oh thank you! I've tested this change in my current project and notices are gone.

**Pull request merged**
