### PR TITLE
DateFormatter: widen typehint to DateTimeInterface

### PR DESCRIPTION
**Pull request by Slamdunk**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

See official doc: https://www.php.net/manual/en/intldateformatter.format.php#refsect1-intldateformatter.format-parameters

### CODE REVIEW

**Comment by michalbundyra** [comment]
@Slamdunk Thanks for your PR. As I see in PHP documentation the other possible value is also [` IntlCalendar`](https://www.php.net/manual/en/class.intlcalendar.php) object.

https://www.php.net/manual/en/intldateformatter.format.php

Do you think is it worth adding it here, as well?

**Comment by Slamdunk** [comment]
Done

**Comment by froschdesign** [comment]
@michalbundyra 
Good catch! 

@Slamdunk 
It would be great if you can add also an example to the documentation and update the first sentence of "Basic Usage".

https://docs.laminas.dev/laminas-i18n/view-helpers/date-format/#basic-usage

**Comment by Slamdunk** [comment]
>  It would be great if you can add also an example to the documentation and update the first sentence of "Basic Usage".

I can update the first sentence, but honestly I have no idea of what exactly `IntlCalendar` is and what purpose it serves, so it's tricky for me to write a meaningful example (beside instantiating the class with spare values) :(

**Comment by froschdesign** [comment]
@Slamdunk 
I created a pull request for the documentation: #30

**Comment by michalbundyra** [comment]
Thanks, @Slamdunk!

**Pull request closed without merging**
